# Generated by Django 3.2.6 on 2021-09-09 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robbery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victim_name', models.CharField(max_length=50, verbose_name='اسم الضحية')),
                ('victim_national_id', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{11}', 'Only digit characters.')], verbose_name='رقم البطاقه الوطنيه لضحية')),
                ('victim_phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{10}', 'Only digit characters.')], verbose_name='رقم جوال الضحية')),
                ('embezzled_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='المبلغ الذي تمت سرقته من الضحية')),
                ('outboard_transferred', models.CharField(choices=[('direct', 'مباشرة'), ('mediator', 'عبر وسيط')], max_length=50, verbose_name='هل تم التحويل للخارج مباشره')),
                ('mediator_ip', models.CharField(blank=True, max_length=150, null=True, verbose_name='اي بي الوسيط')),
                ('gang_ip', models.CharField(max_length=150, verbose_name='اي بي العصابة')),
            ],
            options={
                'verbose_name': 'الضحية',
                'verbose_name_plural': 'الضحية',
            },
        ),
    ]
