# Generated by Django 3.2.6 on 2021-08-31 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip_number', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'Thief',
                'verbose_name_plural': 'Thief',
            },
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip_number', models.GenericIPAddressField()),
                ('embezzled_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('thief', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thief.thief')),
            ],
            options={
                'verbose_name': 'Victim',
                'verbose_name_plural': 'Victim',
            },
        ),
    ]
