# Generated by Django 3.2.6 on 2021-08-31 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thief', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thief',
            name='ip_number',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='thief',
            field=models.ForeignKey(help_text="Thief ip number, in case you didn't`t find it go to thief form and add it, link is down bellow", null=True, on_delete=django.db.models.deletion.SET_NULL, to='thief.thief'),
        ),
    ]
