# Generated by Django 3.2.6 on 2021-08-31 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thief', '0002_auto_20210831_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='thief',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thief.thief'),
        ),
    ]
