# Generated by Django 3.2.6 on 2021-08-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thief', '0003_alter_victim_thief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thief',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
